// ── Realistic dummy data for ACS Business Suite demo mode ──────────────────

export const DEMO_CLIENTS = [
  {
    id: 'c1', name: 'Sharma Traders',
    phone: '9800011001', whatsapp: '9800011001',
    business_type: 'Retail', products_used: 'TallyPrime Silver (Annual Rental)',
    start_date: '2023-04-01', expiry_date: '2025-05-20',
    amount_ex_gst: 8100, amount_incl_gst: 9558,
    notes: 'Key client — owner Rakesh Sharma. Prefers evening calls.',
    created_by: 'demo-admin', created_at: '2023-04-01T10:00:00Z',
  },
  {
    id: 'c2', name: 'Gupta Pharmaceuticals',
    phone: '9800022002', whatsapp: '9800022002',
    business_type: 'Pharma', products_used: 'BUSY Emerald + Marg on Cloud',
    start_date: '2024-01-10', expiry_date: '2026-01-10',
    amount_ex_gst: 16669, amount_incl_gst: 19669,
    notes: 'Upgraded from BUSY Saffron in Jan 2024. Very satisfied.',
    created_by: 'demo-sales', created_at: '2024-01-10T11:00:00Z',
  },
  {
    id: 'c3', name: 'Bengal Rice Mills',
    phone: '9800033003', whatsapp: '9800033003',
    business_type: 'Manufacturing', products_used: 'Dollar ERP Premium (Multi) + VPS SSD-8G',
    start_date: '2022-06-15', expiry_date: '2025-04-10',
    amount_ex_gst: 77400, amount_incl_gst: 91332,
    notes: 'Large client. 12 users. Owner: Dilip Paul. Very price sensitive.',
    created_by: 'demo-admin', created_at: '2022-06-15T09:30:00Z',
  },
  {
    id: 'c4', name: 'Krishnanagar Wholesale',
    phone: '9800044004', whatsapp: '9800044004',
    business_type: 'Distribution', products_used: 'Marg ERP Gold + Marg on Cloud (5 users)',
    start_date: '2024-04-01', expiry_date: '2026-04-01',
    amount_ex_gst: 54000, amount_incl_gst: 63720,
    notes: null,
    created_by: 'demo-sales', created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'c5', name: 'Hotel Aryan Palace',
    phone: '9800055005', whatsapp: '9800055005',
    business_type: 'Hotel/Restaurant', products_used: 'Stayerly Growth',
    start_date: '2025-02-01', expiry_date: '2025-06-01',
    amount_ex_gst: 25000, amount_incl_gst: 29500,
    notes: 'New hotel, 30 rooms. Owner Priya Singh. Interested in Stayerly Scale next year.',
    created_by: 'demo-sales', created_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'c6', name: "M/s Dey & Sons",
    phone: '9800066006', whatsapp: '9800066006',
    business_type: 'Trading', products_used: 'TallyPrime Gold (Annual Rental)',
    start_date: '2024-07-01', expiry_date: '2026-07-01',
    amount_ex_gst: 24300, amount_incl_gst: 28674,
    notes: null,
    created_by: 'demo-sales', created_at: '2024-07-01T10:00:00Z',
  },
  {
    id: 'c7', name: 'Eastern Agro Services',
    phone: '9800077007', whatsapp: '9800077007',
    business_type: 'Services', products_used: 'BUSY Blue (Annual Subscription)',
    start_date: '2024-06-01', expiry_date: '2025-05-28',
    amount_ex_gst: 4999, amount_incl_gst: 5899,
    notes: 'Small firm, 2 users. May upgrade to Saffron.',
    created_by: 'demo-telecaller', created_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'c8', name: 'Raj Steel Industries',
    phone: '9800088008', whatsapp: '9800088008',
    business_type: 'Manufacturing', products_used: 'Dollar ERP Standard (Multi) + VPS SSD-6G',
    start_date: '2023-09-01', expiry_date: '2025-09-01',
    amount_ex_gst: 57600, amount_incl_gst: 67968,
    notes: 'Industrial client, Asansol. 8 users. Contact: Ramesh Agarwal, GM.',
    created_by: 'demo-admin', created_at: '2023-09-01T10:00:00Z',
  },
  {
    id: 'c9', name: 'New Age Retail Pvt Ltd',
    phone: '9800099009', whatsapp: '9800099009',
    business_type: 'Retail', products_used: 'BUSY Saffron + Tally on Cloud (3 users)',
    start_date: '2025-01-15', expiry_date: '2026-01-15',
    amount_ex_gst: 24010, amount_incl_gst: 28332,
    notes: 'Chain of 3 shops. Needs WhatsApp integration next renewal.',
    created_by: 'demo-sales', created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'c10', name: 'Banerjee Chemicals',
    phone: '9800100010', whatsapp: '9800100010',
    business_type: 'Pharma', products_used: 'BUSY Emerald (Annual Subscription)',
    start_date: '2023-03-01', expiry_date: '2025-03-01',
    amount_ex_gst: 9999, amount_incl_gst: 11799,
    notes: 'Expired 2 months ago. Owner not responding to calls. Try WhatsApp.',
    created_by: 'demo-admin', created_at: '2023-03-01T10:00:00Z',
  },
  {
    id: 'c11', name: 'Durgapur Fasteners Ltd',
    phone: '9800111011', whatsapp: '9800111011',
    business_type: 'Manufacturing', products_used: 'Dollar ERP Premium (Single)',
    start_date: '2024-08-01', expiry_date: '2025-08-01',
    amount_ex_gst: 25200, amount_incl_gst: 29736,
    notes: null,
    created_by: 'demo-sales', created_at: '2024-08-01T10:00:00Z',
  },
  {
    id: 'c12', name: 'West Bengal Foodstuff',
    phone: '9800122012', whatsapp: '9800122012',
    business_type: 'Distribution', products_used: 'Marg ERP Silver',
    start_date: '2024-05-01', expiry_date: '2025-06-10',
    amount_ex_gst: 18140, amount_incl_gst: 21405,
    notes: 'Renewal due soon. Interested in adding cloud hosting.',
    created_by: 'demo-sales', created_at: '2024-05-01T10:00:00Z',
  },
  {
    id: 'c13', name: 'Sunita Fashion Store',
    phone: '9800133013', whatsapp: '9800133013',
    business_type: 'Retail', products_used: 'TallyPrime Silver (Annual Rental)',
    start_date: '2025-03-01', expiry_date: '2026-03-01',
    amount_ex_gst: 8100, amount_incl_gst: 9558,
    notes: null,
    created_by: 'demo-telecaller', created_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'c14', name: 'Pioneer Hospitality',
    phone: '9800144014', whatsapp: '9800144014',
    business_type: 'Hotel/Restaurant', products_used: 'Stayerly Scale + Team Page Standard',
    start_date: '2024-11-01', expiry_date: '2025-11-01',
    amount_ex_gst: 48600, amount_incl_gst: 57348,
    notes: '45-room hotel. Flagship client. Owner: Sanjay Mehta.',
    created_by: 'demo-admin', created_at: '2024-11-01T10:00:00Z',
  },
  {
    id: 'c15', name: 'Chandra IT Solutions',
    phone: '9800155015', whatsapp: '9800155015',
    business_type: 'Services', products_used: 'BUSY Blue + App Hosting no-SQL (2 users)',
    start_date: '2025-01-01', expiry_date: '2026-01-01',
    amount_ex_gst: 18860, amount_incl_gst: 22255,
    notes: 'IT firm. 2 locations — Burdwan and Bolpur.',
    created_by: 'demo-sales', created_at: '2025-01-01T10:00:00Z',
  },
]

export const DEMO_QUOTES = [
  {
    id: 'q1', client_name: 'Sharma Traders', business_type: 'Retail', users: 1,
    items: [
      { id: 'tp-silver-ar', product_name: 'TallyPrime Silver', brand: 'Tally', category: 'Accounting', variant: 'Annual Rental', eu_price: 8100, cost_price: 6966, quantity: 1, discount_pct: 0, private_note: '' },
    ],
    total_eu: 8100, total_cost: 6966, total_profit: 1134,
    gst_included: true, notes: 'Annual renewal quote.',
    validity_date: '2025-05-30', status: 'sent',
    created_by: 'demo-sales', created_at: '2025-05-10T10:00:00Z',
    profiles: { full_name: 'Demo Sales' },
  },
  {
    id: 'q2', client_name: 'Bengal Rice Mills', business_type: 'Manufacturing', users: 12,
    items: [
      { id: 'dollar-prem-m', product_name: 'Dollar ERP Premium', brand: 'Dollar', category: 'ERP', variant: 'Multi User', eu_price: 36000, cost_price: 18720, quantity: 1, discount_pct: 5, private_note: 'Negotiated 5% for large deal' },
      { id: 'vps-ssd-8g-yr', product_name: 'VPS SSD-8G', brand: 'Cloudmitra', category: 'VPS', variant: 'Yearly', eu_price: 41400, cost_price: 26662, quantity: 1, discount_pct: 0, private_note: '' },
    ],
    total_eu: 75630, total_cost: 44182, total_profit: 31448,
    gst_included: false, notes: 'Subject to 5% discount on ERP. Payment: 50% advance.',
    validity_date: '2025-05-25', status: 'accepted',
    created_by: 'demo-admin', created_at: '2025-05-08T14:00:00Z',
    profiles: { full_name: 'Demo Admin' },
  },
  {
    id: 'q3', client_name: 'Hotel Aryan Palace', business_type: 'Hotel/Restaurant', users: 3,
    items: [
      { id: 'stayerly-growth', product_name: 'Stayerly Growth', brand: 'Block Edge', category: 'Hospitality', variant: 'Annual', eu_price: 25000, cost_price: 17500, quantity: 1, discount_pct: 0, private_note: '' },
      { id: 'tp-standard', product_name: 'Team Page Standard', brand: 'Block Edge', category: 'Business Tools', variant: 'Annual', eu_price: 3600, cost_price: 2520, quantity: 1, discount_pct: 0, private_note: 'Upsell opportunity' },
    ],
    total_eu: 28600, total_cost: 20020, total_profit: 8580,
    gst_included: true, notes: 'Includes free onboarding support for first 30 days.',
    validity_date: '2025-05-22', status: 'draft',
    created_by: 'demo-sales', created_at: '2025-05-12T16:00:00Z',
    profiles: { full_name: 'Demo Sales' },
  },
  {
    id: 'q4', client_name: 'Krishnanagar Wholesale', business_type: 'Distribution', users: 5,
    items: [
      { id: 'marg-gold', product_name: 'Marg ERP Gold', brand: 'Marg', category: 'ERP', variant: 'Perpetual', eu_price: 25200, cost_price: 17640, quantity: 1, discount_pct: 0, private_note: '' },
      { id: 'cloud-marg-yr', product_name: 'Marg on Cloud', brand: 'Cloudmitra', category: 'Cloud Hosting', variant: 'Yearly/User', eu_price: 5670, cost_price: 3402, quantity: 5, discount_pct: 0, private_note: '' },
    ],
    total_eu: 53550, total_cost: 34650, total_profit: 18900,
    gst_included: false, notes: null,
    validity_date: '2025-06-01', status: 'sent',
    created_by: 'demo-sales', created_at: '2025-05-13T11:00:00Z',
    profiles: { full_name: 'Demo Sales' },
  },
  {
    id: 'q5', client_name: 'Chandra IT Solutions', business_type: 'Services', users: 2,
    items: [
      { id: 'busy-blue-sub', product_name: 'BUSY Blue', brand: 'BUSY', category: 'Accounting', variant: 'Annual Subscription', eu_price: 4999, cost_price: 3249, quantity: 1, discount_pct: 0, private_note: '' },
      { id: 'cloud-app-nosql-yr', product_name: 'App Hosting no-SQL', brand: 'Cloudmitra', category: 'Cloud Hosting', variant: 'Yearly/User', eu_price: 6930, cost_price: 3969, quantity: 2, discount_pct: 0, private_note: '' },
    ],
    total_eu: 18859, total_cost: 11187, total_profit: 7672,
    gst_included: true, notes: null,
    validity_date: '2025-06-05', status: 'accepted',
    created_by: 'demo-sales', created_at: '2025-05-01T10:00:00Z',
    profiles: { full_name: 'Demo Sales' },
  },
]

export const DEMO_TICKETS = [
  {
    id: 't1', title: 'TallyPrime not launching after Windows update',
    description: 'Client reports TallyPrime Silver stopped launching after a Windows security update on 10th May. Error: "MSVCR120.dll missing".',
    priority: 'High', category: 'Technical', status: 'in_progress',
    assigned_to: 'demo-support', created_by: 'demo-sales',
    created_at: '2025-05-11T09:30:00Z', resolved_at: null,
    assigned_profile: { full_name: 'Demo Support' },
    creator_profile: { full_name: 'Demo Sales' },
    client_name: 'Sharma Traders',
  },
  {
    id: 't2', title: 'Invoice GST calculation incorrect — BUSY Emerald',
    description: 'Client says GST is being calculated at 12% instead of 18% for some product categories. Needs urgent fix before month end.',
    priority: 'Urgent', category: 'Technical', status: 'open',
    assigned_to: null, created_by: 'demo-telecaller',
    created_at: '2025-05-13T11:15:00Z', resolved_at: null,
    assigned_profile: null,
    creator_profile: { full_name: 'Demo Telecaller' },
    client_name: 'Gupta Pharmaceuticals',
  },
  {
    id: 't3', title: 'Request for Stayerly Scale upgrade quote',
    description: 'Pioneer Hospitality wants to upgrade from Stayerly Growth to Scale. Expanding to 2nd property with 45 rooms.',
    priority: 'Medium', category: 'New requirement', status: 'open',
    assigned_to: 'demo-sales', created_by: 'demo-admin',
    created_at: '2025-05-10T14:00:00Z', resolved_at: null,
    assigned_profile: { full_name: 'Demo Sales' },
    creator_profile: { full_name: 'Demo Admin' },
    client_name: 'Pioneer Hospitality',
  },
  {
    id: 't4', title: 'VPS SSD-8G — server unreachable since morning',
    description: 'Bengal Rice Mills reporting their VPS is not accessible. Remote desktop connection timing out. All 12 users affected.',
    priority: 'Urgent', category: 'Technical', status: 'pending_client',
    assigned_to: 'demo-support', created_by: 'demo-support',
    created_at: '2025-05-14T08:45:00Z', resolved_at: null,
    assigned_profile: { full_name: 'Demo Support' },
    creator_profile: { full_name: 'Demo Support' },
    client_name: 'Bengal Rice Mills',
  },
  {
    id: 't5', title: 'Billing query — extra charge on last invoice',
    description: 'Client received invoice for ₹29,736 but expected ₹25,200. Needs clarification on GST breakup.',
    priority: 'Low', category: 'Billing', status: 'resolved',
    assigned_to: 'demo-sales', created_by: 'demo-telecaller',
    created_at: '2025-05-09T10:00:00Z', resolved_at: '2025-05-09T15:30:00Z',
    assigned_profile: { full_name: 'Demo Sales' },
    creator_profile: { full_name: 'Demo Telecaller' },
    client_name: 'Durgapur Fasteners Ltd',
  },
  {
    id: 't6', title: 'Need training session for new operator — Dollar ERP',
    description: 'Raj Steel hired a new accounts operator. Requesting 1-hour remote training on Dollar ERP Standard.',
    priority: 'Low', category: 'General', status: 'open',
    assigned_to: 'demo-support', created_by: 'demo-sales',
    created_at: '2025-05-12T16:30:00Z', resolved_at: null,
    assigned_profile: { full_name: 'Demo Support' },
    creator_profile: { full_name: 'Demo Sales' },
    client_name: 'Raj Steel Industries',
  },
  {
    id: 't7', title: 'Marg on Cloud — slow performance during peak hours',
    description: 'Krishnanagar Wholesale reporting that Marg on Cloud becomes very slow between 11 AM – 1 PM. All 5 users face lag.',
    priority: 'High', category: 'Technical', status: 'in_progress',
    assigned_to: 'demo-support', created_by: 'demo-sales',
    created_at: '2025-05-13T17:00:00Z', resolved_at: null,
    assigned_profile: { full_name: 'Demo Support' },
    creator_profile: { full_name: 'Demo Sales' },
    client_name: 'Krishnanagar Wholesale',
  },
  {
    id: 't8', title: 'WhatsApp integration request for BUSY Saffron',
    description: 'New Age Retail wants to send invoices via WhatsApp directly from BUSY. Enquiring about Tally WhatsApp or Message Rider add-on.',
    priority: 'Medium', category: 'New requirement', status: 'open',
    assigned_to: 'demo-sales', created_by: 'demo-telecaller',
    created_at: '2025-05-14T12:00:00Z', resolved_at: null,
    assigned_profile: { full_name: 'Demo Sales' },
    creator_profile: { full_name: 'Demo Telecaller' },
    client_name: 'New Age Retail Pvt Ltd',
  },
]

export const DEMO_TICKET_COMMENTS = {
  t1: [
    { id: 'tc1', ticket_id: 't1', user_id: 'demo-support', comment: 'Checked — it\'s a Visual C++ redistributable issue. Downloading MSVCR120.dll installer now.', created_at: '2025-05-11T10:15:00Z', profiles: { full_name: 'Demo Support' } },
    { id: 'tc2', ticket_id: 't1', user_id: 'demo-sales', comment: 'Client is waiting. Please resolve ASAP — they have month-end entries pending.', created_at: '2025-05-11T11:00:00Z', profiles: { full_name: 'Demo Sales' } },
    { id: 'tc3', ticket_id: 't1', user_id: 'demo-support', comment: 'Shared TeamViewer session. Installing VC++ 2013 redistributable. Will update in 30 min.', created_at: '2025-05-11T11:30:00Z', profiles: { full_name: 'Demo Support' } },
  ],
  t4: [
    { id: 'tc4', ticket_id: 't4', user_id: 'demo-support', comment: 'Raised ticket with Cloudmitra support. They are investigating at datacenter level.', created_at: '2025-05-14T09:30:00Z', profiles: { full_name: 'Demo Support' } },
    { id: 'tc5', ticket_id: 't4', user_id: 'demo-support', comment: 'Cloudmitra confirmed network maintenance in progress. ETA 2 hours. Client informed.', created_at: '2025-05-14T10:00:00Z', profiles: { full_name: 'Demo Support' } },
  ],
  t5: [
    { id: 'tc6', ticket_id: 't5', user_id: 'demo-sales', comment: 'Explained GST breakup — ₹25,200 + 18% GST = ₹29,736. Sent detailed invoice breakdown via WhatsApp.', created_at: '2025-05-09T15:30:00Z', profiles: { full_name: 'Demo Sales' } },
  ],
  t7: [
    { id: 'tc7', ticket_id: 't7', user_id: 'demo-support', comment: 'Checking server CPU and RAM usage during peak hours. Might need to upgrade to App Hosting SQL.', created_at: '2025-05-14T09:00:00Z', profiles: { full_name: 'Demo Support' } },
  ],
}

export const DEMO_CALL_LOGS = [
  { id: 'cl1', client_id: 'c10', telecaller_id: 'demo-telecaller', called_at: '2025-05-14T11:00:00Z', outcome: 'No answer', notes: 'Tried 3 times. No response.', callback_date: '2025-05-16', clients: { name: 'Banerjee Chemicals', phone: '9800100010' }, profiles: { full_name: 'Demo Telecaller' } },
  { id: 'cl2', client_id: 'c5', telecaller_id: 'demo-telecaller', called_at: '2025-05-14T11:30:00Z', outcome: 'Interested', notes: 'Owner interested in renewal. Said she will confirm by Friday. Quote already shared.', callback_date: '2025-05-16', clients: { name: 'Hotel Aryan Palace', phone: '9800055005' }, profiles: { full_name: 'Demo Telecaller' } },
  { id: 'cl3', client_id: 'c7', telecaller_id: 'demo-telecaller', called_at: '2025-05-14T12:00:00Z', outcome: 'Callback scheduled', notes: 'Owner busy. Asked to call Monday 10 AM.', callback_date: '2025-05-19', clients: { name: 'Eastern Agro Services', phone: '9800077007' }, profiles: { full_name: 'Demo Telecaller' } },
  { id: 'cl4', client_id: 'c12', telecaller_id: 'demo-telecaller', called_at: '2025-05-14T12:30:00Z', outcome: 'Interested', notes: 'Confirmed renewal. Also asked about cloud hosting. Sales to follow up.', callback_date: null, clients: { name: 'West Bengal Foodstuff', phone: '9800122012' }, profiles: { full_name: 'Demo Telecaller' } },
  { id: 'cl5', client_id: 'c3', telecaller_id: 'demo-telecaller', called_at: '2025-05-13T10:00:00Z', outcome: 'Closed', notes: 'Renewal confirmed. Payment received. Updated expiry to next year.', callback_date: null, clients: { name: 'Bengal Rice Mills', phone: '9800033003' }, profiles: { full_name: 'Demo Telecaller' } },
  { id: 'cl6', client_id: 'c1', telecaller_id: 'demo-telecaller', called_at: '2025-05-13T11:00:00Z', outcome: 'Interested', notes: 'Rakesh bhai confirmed renewal. Sending quote now.', callback_date: null, clients: { name: 'Sharma Traders', phone: '9800011001' }, profiles: { full_name: 'Demo Telecaller' } },
  { id: 'cl7', client_id: 'c10', telecaller_id: 'demo-telecaller', called_at: '2025-05-13T14:00:00Z', outcome: 'Not interested', notes: 'Owner says moving to different software. Could not convince.', callback_date: null, clients: { name: 'Banerjee Chemicals', phone: '9800100010' }, profiles: { full_name: 'Demo Telecaller' } },
  { id: 'cl8', client_id: 'c7', telecaller_id: 'demo-telecaller', called_at: '2025-05-12T10:00:00Z', outcome: 'No answer', notes: '', callback_date: '2025-05-14', clients: { name: 'Eastern Agro Services', phone: '9800077007' }, profiles: { full_name: 'Demo Telecaller' } },
]

export const DEMO_SESSIONS = [
  { id: 's1', user_id: 'demo-telecaller', login_at: '2025-05-14T09:00:00Z', logout_at: '2025-05-14T13:15:00Z', total_calls: 4, profiles: { full_name: 'Demo Telecaller' } },
  { id: 's2', user_id: 'demo-telecaller', login_at: '2025-05-13T09:30:00Z', logout_at: '2025-05-13T14:00:00Z', total_calls: 3, profiles: { full_name: 'Demo Telecaller' } },
  { id: 's3', user_id: 'demo-telecaller', login_at: '2025-05-12T09:00:00Z', logout_at: '2025-05-12T12:30:00Z', total_calls: 2, profiles: { full_name: 'Demo Telecaller' } },
]

export const DEMO_STAFF = [
  { id: 'demo-admin',      email: 'admin@demo.com',      full_name: 'Demo Admin',      role: 'admin',      is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 'demo-sales',      email: 'sales@demo.com',      full_name: 'Demo Sales',      role: 'sales',      is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 'demo-telecaller', email: 'telecaller@demo.com', full_name: 'Demo Telecaller', role: 'telecaller', is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 'demo-support',    email: 'support@demo.com',    full_name: 'Demo Support',    role: 'support',    is_active: true, created_at: '2024-01-01T00:00:00Z' },
]
